name: Scheduled Dependency Check Maven

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 6"

jobs:

  dependency-check-maven:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Execute OWASP dependency check
        run: mvn clean install -P security-updates -DskipTests=true -B
